<!DOCTYPE html>
<html>
<head>
    <title>Expense Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header img {
            max-width: 150px;
            height: auto;
        }
        .header h1 {
            margin: 10px 0;
        }
        .header p {
            margin: 5px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        table, th, td {
            border: 1px solid #ddd;
        }
        th, td {
            padding: 12px;
            text-align: left;
        }
        th {
            background-color: #f4f4f4;
            color: #333;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        tr:hover {
            background-color: #f1f1f1;
        }
        .currency-symbol {
            font-size: 1.2em;
            vertical-align: middle;
        }
        .footer {
            margin-top: 20px;
            text-align: center;
        }
        .footer p {
            margin: 5px 0;
        }
    </style>
</head>
<body>
    <div class="header">
        <img src="{{ public_path('auth/logo.png') }}" alt="Company Logo">
        <h1>Expense Report</h1>
        <p><strong>Report Date:</strong> {{ \Carbon\Carbon::now()->format('F j, Y') }}</p>
        <p><strong>Generated By:</strong> {{ Auth::user()->name }}</p>
        <p><strong>Period:</strong>
            {{ isset($fromDate) ? \Carbon\Carbon::parse($fromDate)->format('F j, Y') : 'N/A' }}
            to
            {{ isset($toDate) ? \Carbon\Carbon::parse($toDate)->format('F j, Y') : 'N/A' }}
        </p>
    </div>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Date</th>
                <th>Amount</th>
                <th>Category</th>
                <th>Entry By</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($expenses as $expense)
                <tr>
                    <td>{{ $expense->id }}</td>
                    <td>{{ \Carbon\Carbon::parse($expense->expense_date)->format('Y-m-d') }}</td>
                    <td>৳ {{ number_format($expense->amount, 2) }}</td>
                    <td>{{ $expense->expense_category }}</td>
                    <td>{{ $expense->staff->name ?? 'N/A' }}</td>
                    <td>{{ $expense->description }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <div class="footer">
        <p>Generated by {{ config('app.name') }}</p>
        <p>For internal use only</p>
    </div>
</body>
</html>
