@php
    use App\Models\User;
@endphp
<!DOCTYPE html>
<html>
<head>
    <title>Expense Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header img {
            max-width: 150px;
            height: auto;
        }
        .header h1 {
            margin: 10px 0;
        }
        .header p {
            margin: 5px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        table, th, td {
            border: 1px solid #ddd;
            font-size: 12px;
        }
        th, td {
            padding: 12px;
            text-align: left;
        }
        th {
            background-color: #f4f4f4;
            color: #333;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        tr:hover {
            background-color: #f1f1f1;
        }
        .currency-symbol {
            font-size: 1.2em;
            vertical-align: middle;
        }
        .footer {
            margin-top: 20px;
            text-align: center;
        }
        .footer p {
            margin: 5px 0;
        }
        .signatures {
            margin-top: 20px;
            padding: 10px;
            border-top: 2px solid #ddd;
        }
        .signatures div {
            display: inline-block;
            width: 30%;
            text-align: center;
        }
        .signatures div p {
            margin: 0;
            padding: 5px 0;
        }
        .signatures div .signature-line {
            border-top: 1px solid #000;
            width: 100%;
            margin: 10px auto;
        }
    </style>
</head>
<body>
    <div class="header">
        <img src="{{ public_path('auth/logo.png') }}" alt="Company Logo">
        <h1>Expense Report</h1>
        <p><strong>Report Date:</strong> {{ \Carbon\Carbon::now()->format('F j, Y') }}</p>
        <p><strong>Period:</strong>
            {{ $fromDate ? \Carbon\Carbon::parse($fromDate)->format('F j, Y') : 'N/A' }}
            to
            {{ $toDate ? \Carbon\Carbon::parse($toDate)->format('F j, Y') : 'N/A' }}
        </p>
        <p><strong>Category:</strong>
            {{ $category ? $category : 'All Categories' }}
        </p>
    </div>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Date</th>
                <th>Amount</th>
                <th>Category</th>
                <th>Entry By</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            @php
                $sl = 1;
            @endphp
            @foreach ($expenses as $expense)
                <tr>
                    <td>{{ $sl }}</td>
                    <td>{{ \Carbon\Carbon::parse($expense->expense_date)->format('Y-m-d') }}</td>
                    <td>{{ number_format($expense->amount, 2) }}</td>
                    <td>{{ $expense->expense_category }}</td>
                    <td>{{ $expense->staff->name ?? 'N/A' }}</td>
                    <td>{{ $expense->description }}</td>
                </tr>
                @php
                    $sl++;
                @endphp
            @endforeach
            <tr>
                <td></td>
                <td>Total = </td>
                <td>{{ $totalAmount . " Taka"}}</td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </tbody>
    </table>
    <div class="signatures">
        <div>
            <p><strong>Generated By:</strong></p>
            <div class="signature-line"></div>
            {{-- <p>{{ Auth::user()->name }}</p> --}}
            <img style="width: 75px;" src="https://www.shutterstock.com/image-vector/fake-autograph-samples-handdrawn-signatures-260nw-2325821623.jpg" alt="">
        </div>
        <div>
            <p><strong>Checked By:</strong></p>
            <div class="signature-line"></div>
            {{-- <p>{{ User::where('role', 'hr')->pluck('name')->first() }}</p> --}}
            <img style="width: 75px;" src="https://www.shutterstock.com/image-vector/fake-autograph-samples-handdrawn-signatures-260nw-2325821623.jpg" alt="">
        </div>
        <div>
            <p><strong>Approved By:</strong></p>
            <div class="signature-line"></div>
            {{-- <p>{{ User::where('role', 'ceo')->pluck('name')->first() }}</p> --}}
            <img style="width: 75px;" src="https://www.shutterstock.com/image-vector/fake-autograph-samples-handdrawn-signatures-260nw-2325821623.jpg" alt="">
        </div>
    </div>
    <div class="footer">
        <p>Generated by {{ config('app.name') }}</p>
        <p>For internal use only</p>
    </div>
</body>
</html>
